### ISSUE TITLE
Refresh Stream button returns 400 status code for Nest camera

### ISSUE THREAD

**Issue by thedanfernandez** [google/device-access-sample-web-app#2]
### Overview
The `Refresh Stream` button in the [live demo](https://device-access-sample.web.app) and local instances of this app are returning 400 errors.

### Repro

1. Setup the app and device management per instructions, enable permission to a Google Nest camera (v2 wired).
2. Login using ID, Secret, Project ID as mentioned in the project
3. Click `Camera Stream` and you will successfully get a live stream!
4. Now click `Refresh Stream` and you will get the following 400 status code:

**Post Response**
```json
{
  "error": {
    "code": 400,
    "message": "WebRtc error caused by invalid session or user id mismatch.",
    "status": "FAILED_PRECONDITION"
  }
}
````

### Potential cause
In looking at the Post Request log, I see the `Payload` params has an empty `mediaSessionId` as you can see in the Request snippet:

**Post Request** - Note: I removed the endpoint and auth bearer token

```javascript
/// Endpoint ...
/// Authorization ..
Payload: 
{
    "command": "sdm.devices.commands.CameraLiveStream.ExtendWebRtcStream",
    "params": {
        "mediaSessionId": ""
    }
}
```

**Comment by hemslo** [comment]
I'm testing my nest camera and have the same error, that's because [GenerateWebRtcStream](https://developers.google.com/nest/device-access/traits/device/camera-live-stream#generatewebrtcstream) returns `mediaSessionId`, instead of `streamExtensionToken` for [GenerateRtspStream](https://developers.google.com/nest/device-access/traits/device/camera-live-stream#generatertspstream).
I'll create a PR to handle both cases.
